/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddItem: typeof import('./src/components/items/AddItem.vue')['default']
    DemandDetail: typeof import('./src/components/layout/main/DemandDetail.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FooterComponent: typeof import('./src/components/layout/footer/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/layout/header/HeaderComponent.vue')['default']
    ItemCard: typeof import('./src/components/items/ItemCard.vue')['default']
    LoginByPassword: typeof import('./src/components/Login/LoginByPassword.vue')['default']
    LoginByPhone: typeof import('./src/components/Login/LoginByPhone.vue')['default']
    LoginInput: typeof import('./src/components/Login/LoginInput.vue')['default']
    MainComponent: typeof import('./src/components/layout/main/MainComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateUserInfo: typeof import('./src/components/Login/UpdateUserInfo.vue')['default']
  }
}
